{{- range $componentName, $component := .Values.components -}}
{{- if and (ne $component.type "cronjob") (ne $component.type "pre-job") -}}
{{- $kubeLabels := (merge (dict "name" $.Release.Name "instance" (printf "%s-%d" (include "component.name" (dict "name" $componentName "Release" $.Release)) $.Release.Revision) "component" $componentName) $.Values.global.metadata) -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "component.name" (dict "name" $componentName "Release" $.Release) }}
  labels:
    {{ include "cookielab.kubernetes.labels" $kubeLabels | indent 4 | trim }}
    {{ include "cookielab.kubernetes.labels.selector" $kubeLabels | indent 4 | trim }}
    {{- if $.Values.global.metadata.labels }}
    {{ $.Values.global.metadata.labels | toYaml | nindent 4 }}
    {{- end }}
  annotations:
    {{ include "cookielab.kubernetes.annotations" (dict "defaultContainer" "application") | indent 4 | trim }}
    {{- if $.Values.global.metadata.annotations }}
    {{ $.Values.global.metadata.annotations | toYaml | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ $component.replicas }}
  progressDeadlineSeconds: {{ default 300 $component.progressDeadlineSeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ coalesce (index $component "rollingUpdate" | default dict).maxUnavailable $.Values.global.rollingUpdate.maxUnavailable | quote}}
      maxSurge: {{ coalesce (index $component "rollingUpdate" | default dict).maxSurge $.Values.global.rollingUpdate.maxSurge | quote}}
  selector:
    matchLabels:
      {{ include "cookielab.kubernetes.labels.selector" $kubeLabels | indent 6 | trim }}
  template:
    metadata:
      labels:
        {{ include "cookielab.kubernetes.labels" $kubeLabels | indent 8 | trim }}
        {{ include "cookielab.kubernetes.labels.selector" $kubeLabels | indent 8 | trim }}
        {{- if $.Values.global.metadata.labels }}
        {{ $.Values.global.metadata.labels | toYaml | nindent 8 }}
        {{- end }}
      annotations:
        {{ include "cookielab.kubernetes.annotations" (dict "defaultContainer" "application") | indent 8 | trim }}
        {{- if $.Values.global.metadata.gitlab }}
        {{ include "cookielab.gitlab.annotations" $.Values.global.metadata.gitlab | indent 8 | trim }}
        {{- end }}
        {{ include "cookielab.prometheus.annotations" $.Values.global.prometheus | indent 8 | trim }}
        {{- if $.Values.global.metadata.annotations }}
        {{ $.Values.global.metadata.annotations | toYaml | nindent 8 }}
        {{- end }}
    spec:
      {{ include "pod.spec" (dict "containers" (dict "application" $component) "global" $.Values.global "metadata" $.Values.global.metadata "nodeSelector" $component.nodeSelector "kubeLabels" $kubeLabels "enableServiceLinks" $component.enableServiceLinks "serviceAccountName" $component.serviceAccountName "tolerations" $component.tolerations "imagePullSecrets" $component.imagePullSecrets "volumeMounts" $component.volumeMounts "volumes" $component.volumes "persistentVolumeClaim" $component.persistentVolumeClaim "componentName" (include "component.name" (dict "name" $componentName "Release" $.Release)) "root" $) | indent 6 | trim }}
{{ end -}}
{{- end -}}
